name: gmaps_scraper_app
description: Công cụ thu thập dữ liệu địa điểm Google Maps.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^2.0.3
  get: ^4.1.4
  url_launcher: ^6.0.3
  puppeteer: ^2.0.0
  rome_bus: ^0.0.2
  aes_crypt: ^0.1.1
  platform_device_id: ^1.0.1
  clipboard: ^0.1.3
  sqlite3: ^1.0.0
  sqflite_common_ffi: ^2.0.0
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_macos: ^0.0.4
  intl: ^0.17.0
  excel: ^2.0.0-null-safety
  flutter_easyloading: ^3.0.0
  simple_autocomplete_formfield: ^0.3.0

flutter:
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

  uses-material-design: true
